export const DEFAULT_MOVE_TO_OPTS: MoveToOpts = {
    reusePath: 3,
    visualizePathStyle: {
        stroke: "#ffffff",
    }
}

export const ENERGY_PER_TICK_PER_SOURCE_CENTER_ROOM =
    SOURCE_ENERGY_KEEPER_CAPACITY / ENERGY_REGEN_TIME;
export const ENERGY_PER_TICK_PER_SOURCE_RESERVED_ROOM =
    SOURCE_ENERGY_CAPACITY / ENERGY_REGEN_TIME;
export const ENERGY_PER_TICK_PER_SOURCE_UNRESERVED_ROOM =
    SOURCE_ENERGY_NEUTRAL_CAPACITY / ENERGY_REGEN_TIME;
